{
    "hosts-folder": "/var/run/docker-hosts",
    "no-docker-wait": 60,
    "between-updates-wait": 2,
    "docker-socket": "unix://var/run/docker.sock",
    "dnsmasq-executable": "/usr/local/sbin/dnsmasq",
    "dnsmasq-parameters": [
        "--no-daemon",
        "--clear-on-reload",
        "--no-resolv",
        "--no-hosts",
        "--listen-address=127.0.0.54",
        "--port=53",
        "--hostsdir="
    ]
}
